# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af8b6750a4b3771c9dffee52a8797c79e687081bb408849d36c0ec1a3830cc3a0acbdaa043e0930e1680d37d37075a95a47f041cfa2b7e1dfc80875b232dcad1

test:
  secret_key_base: 9c5f1e763cd1cffd3eeb606d875269e89aeaef1c46e69e4fc3f0b3a1475697bfd934c8d9401315e22069edf3661150c817c8528c327c1f3971256b68caa03994

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
