pull_request_rules:
  - name: automatic merge when CI passes and 1 reviews
    conditions:
      - approved-reviews-by>=1
      - status-success=default
      - base=master
    actions:
      merge:
        method: squash
      delete_head_branch: {}  
