pull_request_rules:
  - name: automatic merge when CI passes and 1 reviews
    conditions:
      - approved-reviews-by>=1
      - status-success=default
      - status-success=Codacy/PR Quality Review
      - base=master
    actions:
      merge:
        method: squash
        strict: true
      delete_head_branch: {}  
