# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d5b13fca6ee04c5194504f69071a0205186e7ada743d594156acb1c863c138d5ffa8e040c5534f1c0dd09c25d1788fda34a144d4eb8ecbbcea599cb04db2c0a

test:
  secret_key_base: a9edccdee744b9568574229801497d82d5210cd89c0377cf239beeb922b04912933bd178e91d7fa1e5e38c6fe0cbbfc45ef4ad01dcad1b6778c7772048a5b61f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
