# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2aaae55d4611df236b74ef3a062b45dac912dea9caab2b14a267bdb06b8498c71bfe905211ede497371e228cd58b28067e0584466aab736e1f7707948e4bd453

test:
  secret_key_base: 4cc84ef579977ed5e27889496dcbdb56d8c2db0b9a7311d0e28d2220f279bf1ca5de820313daffa6a6691dfac28a88b84a887c7d0ec2cfeb7b6739632ce4cf60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
