# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b638b134c6f9b1bf63cff44434b2d593e760a8c073889e80b8d091bf10dc18689f6c7b36bbbb51ffd02a24e584812a7b0e7507528bb8aa6b2e48ea58dc2e636

test:
  secret_key_base: ffeea972dea28fa2f9c04f25da8e512fca56021768748d78db06150993d63317116f1b068cfba8a2d7580563a372a996c85e33e2e1feef7fc640242cf5bb06f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
